# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.auto", false);
user_pref("app.update.disable_button.showUpdateHistory", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1400228457);
user_pref("app.update.lastUpdateTime.background-update-timer", 1400208762);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1400145369);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1400208642);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131025151332");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 595);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20130910160258");
user_pref("browser.startup.homepage_override.mstone", "24.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":2}");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1400231318472");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1400817214130");
user_pref("datareporting.policy.firstRunTime", "1400144918471");
user_pref("datareporting.sessions.current.activeTicks", 9);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 818);
user_pref("datareporting.sessions.current.main", 69);
user_pref("datareporting.sessions.current.sessionRestored", 840);
user_pref("datareporting.sessions.current.startTime", "1400817152345");
user_pref("datareporting.sessions.current.totalTime", 114);
user_pref("datareporting.sessions.currentIndex", 8);
user_pref("datareporting.sessions.previous.0", "{\"s\":1400144912853,\"a\":17,\"t\":88,\"c\":true,\"m\":156,\"fp\":668,\"sr\":8010}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1400145035409,\"a\":4,\"t\":18,\"c\":true,\"m\":484,\"fp\":1034,\"sr\":1092}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1400145248705,\"a\":39,\"t\":198,\"c\":true,\"m\":31,\"fp\":531,\"sr\":581}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1400208521091,\"a\":41,\"t\":257,\"c\":true,\"m\":53,\"fp\":910,\"sr\":968}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1400228336610,\"a\":13,\"t\":164,\"c\":true,\"m\":30,\"fp\":510,\"sr\":563}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1400376306025,\"a\":1,\"t\":3,\"c\":true,\"m\":38,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1400376656303,\"a\":13,\"t\":63,\"c\":true,\"m\":37,\"fp\":416,\"sr\":500}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1400555610180,\"a\":2,\"t\":7,\"c\":true,\"m\":28,\"fp\":552,\"sr\":675}");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1400817138732,\"rdfTime\":1378859500000}}}]");
user_pref("extensions.lastAppVersion", "24.0");
user_pref("extensions.lastPlatformVersion", "24.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130910160258");
user_pref("gecko.mstone", "24.0");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.migrated", true);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("toolkit.startup.last_success", 1400817152);
user_pref("toolkit.telemetry.previousBuildID", "20130910160258");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1402736924);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
