# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1411538941);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1411539061);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1411569644);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1411565924);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 163840);
user_pref("browser.download.lastdir", "/root/Downloads");
user_pref("browser.download.panel.firstSessionCompleted", true);
user_Pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 1435);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20140903223327");
user_pref("browser.startup.homepage_override.mstone", "24.8.0");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1411620371898");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1411539797785");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1411544267456");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1411573071634");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1411453397784");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.firstPaint", 1008);
user_pref("datareporting.sessions.current.main", 81);
user_pref("datareporting.sessions.current.sessionRestored", 1084);
user_pref("datareporting.sessions.current.startTime", "1411620310287");
user_pref("datareporting.sessions.current.totalTime", 5);
user_pref("datareporting.sessions.currentIndex", 13);
user_pref("datareporting.sessions.previous.0", "{\"s\":1411453396843,\"a\":0,\"t\":6,\"c\":false,\"m\":132,\"fp\":2346,\"sr\":2445}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1411454135666,\"a\":0,\"t\":5,\"c\":false,\"m\":72,\"fp\":1953,\"sr\":2117}");
user_pref("datareporting.sessions.previous.10", "{\"s\":1411544107199,\"a\":0,\"t\":5,\"c\":false,\"m\":203,\"fp\":1605,\"sr\":1692}");
user_pref("datareporting.sessions.previous.11", "{\"s\":1411544203561,\"a\":0,\"t\":5,\"c\":false,\"m\":113,\"fp\":1423,\"sr\":1524}");
user_pref("datareporting.sessions.previous.12", "{\"s\":1411619536829,\"a\":0,\"t\":5,\"c\":false,\"m\":104,\"fp\":1089,\"sr\":1180}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1411525855485,\"a\":0,\"t\":5,\"c\":false,\"m\":92,\"fp\":1829,\"sr\":1935}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1411525898669,\"a\":0,\"t\":5,\"c\":false,\"m\":112,\"fp\":1912,\"sr\":2028}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1411526033649,\"a\":0,\"t\":5,\"c\":false,\"m\":62,\"fp\":1161,\"sr\":1253}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1411526914822,\"a\":0,\"t\":6,\"c\":false,\"m\":303,\"fp\":2291,\"sr\":2420}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1411528308461,\"a\":0,\"t\":5,\"c\":false,\"m\":173,\"fp\":1283,\"sr\":1377}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1411537952691,\"a\":0,\"t\":6,\"c\":false,\"m\":382,\"fp\":2642,\"sr\":2734}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1411538748980,\"a\":0,\"t\":5,\"c\":false,\"m\":64,\"fp\":1479,\"sr\":1568}");
user_pref("datareporting.sessions.previous.9", "{\"s\":1411538820354,\"a\":0,\"t\":5,\"c\":false,\"m\":202,\"fp\":1189,\"sr\":1264}");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.8.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1411378866000,\"rdfTime\":1409787290000}}}]");
user_pref("extensions.lastAppVersion", "24.8.0");
user_pref("extensions.lastPlatformVersion", "24.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140903223327");
user_pref("gecko.mstone", "24.8.0");
user_pref("idle.lastDailyNotification", 1411539978);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 5119);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1411620310);
user_pref("toolkit.telemetry.previousBuildID", "20140903223327");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1414045401);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
