# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 14);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20131001024718");
user_pref("browser.slowStartup.averageTime", 1870);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20131001024718");
user_pref("browser.startup.homepage_override.mstone", "25.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1380525540485");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1380439140485");
user_pref("datareporting.sessions.current.activeTicks", 7);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1883);
user_pref("datareporting.sessions.current.main", 72);
user_pref("datareporting.sessions.current.sessionRestored", 1942);
user_pref("datareporting.sessions.current.startTime", "1382428801822");
user_pref("datareporting.sessions.current.totalTime", 35);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1380439140021,\"a\":21,\"t\":104,\"c\":true,\"m\":141,\"fp\":1573,\"sr\":1803}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:25.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1381211418640,\"rdfTime\":1381211418460}}},{\"name\":\"winreg-app-user\",\"addons\":{\"dict@www.youdao.com\":{\"descriptor\":\"C:\\\\Users\\\\czhou\\\\AppData\\\\Local\\\\Youdao\\\\Dict\\\\Application\\\\stable\\\\extensions\\\\firefox\",\"mtime\":1375155808637,\"rdfTime\":1352558376000},\"{1B33E42F-EF14-4cd3-B6DC-174571C4349C}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Thunder Network\\\\Thunder\\\\BHO\\\\Firefox\",\"mtime\":1377574592761,\"rdfTime\":1377574586874}}}]");
user_pref("extensions.lastAppVersion", "25.0");
user_pref("extensions.lastPlatformVersion", "25.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20131001024718");
user_pref("gecko.mstone", "25.0");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.socks", "localhost");
user_pref("network.proxy.socks_port", 2001);
user_pref("network.proxy.type", 1);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1382428801);
user_pref("toolkit.telemetry.previousBuildID", "20131001024718");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1383031146);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
